// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Categories   string
	HTTPSessions string
	Transactions string
	Types        string
	UserTokens   string
	Users        string
}{
	Categories:   "categories",
	HTTPSessions: "http_sessions",
	Transactions: "transactions",
	Types:        "types",
	UserTokens:   "user_tokens",
	Users:        "users",
}
