// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Categories", testCategories)
	t.Run("HTTPSessions", testHTTPSessions)
	t.Run("Transactions", testTransactions)
	t.Run("Types", testTypes)
	t.Run("UserTokens", testUserTokens)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("Categories", testCategoriesDelete)
	t.Run("HTTPSessions", testHTTPSessionsDelete)
	t.Run("Transactions", testTransactionsDelete)
	t.Run("Types", testTypesDelete)
	t.Run("UserTokens", testUserTokensDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Categories", testCategoriesQueryDeleteAll)
	t.Run("HTTPSessions", testHTTPSessionsQueryDeleteAll)
	t.Run("Transactions", testTransactionsQueryDeleteAll)
	t.Run("Types", testTypesQueryDeleteAll)
	t.Run("UserTokens", testUserTokensQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Categories", testCategoriesSliceDeleteAll)
	t.Run("HTTPSessions", testHTTPSessionsSliceDeleteAll)
	t.Run("Transactions", testTransactionsSliceDeleteAll)
	t.Run("Types", testTypesSliceDeleteAll)
	t.Run("UserTokens", testUserTokensSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Categories", testCategoriesExists)
	t.Run("HTTPSessions", testHTTPSessionsExists)
	t.Run("Transactions", testTransactionsExists)
	t.Run("Types", testTypesExists)
	t.Run("UserTokens", testUserTokensExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("Categories", testCategoriesFind)
	t.Run("HTTPSessions", testHTTPSessionsFind)
	t.Run("Transactions", testTransactionsFind)
	t.Run("Types", testTypesFind)
	t.Run("UserTokens", testUserTokensFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("Categories", testCategoriesBind)
	t.Run("HTTPSessions", testHTTPSessionsBind)
	t.Run("Transactions", testTransactionsBind)
	t.Run("Types", testTypesBind)
	t.Run("UserTokens", testUserTokensBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("Categories", testCategoriesOne)
	t.Run("HTTPSessions", testHTTPSessionsOne)
	t.Run("Transactions", testTransactionsOne)
	t.Run("Types", testTypesOne)
	t.Run("UserTokens", testUserTokensOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("Categories", testCategoriesAll)
	t.Run("HTTPSessions", testHTTPSessionsAll)
	t.Run("Transactions", testTransactionsAll)
	t.Run("Types", testTypesAll)
	t.Run("UserTokens", testUserTokensAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("Categories", testCategoriesCount)
	t.Run("HTTPSessions", testHTTPSessionsCount)
	t.Run("Transactions", testTransactionsCount)
	t.Run("Types", testTypesCount)
	t.Run("UserTokens", testUserTokensCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("Categories", testCategoriesHooks)
	t.Run("HTTPSessions", testHTTPSessionsHooks)
	t.Run("Transactions", testTransactionsHooks)
	t.Run("Types", testTypesHooks)
	t.Run("UserTokens", testUserTokensHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Categories", testCategoriesInsert)
	t.Run("Categories", testCategoriesInsertWhitelist)
	t.Run("HTTPSessions", testHTTPSessionsInsert)
	t.Run("HTTPSessions", testHTTPSessionsInsertWhitelist)
	t.Run("Transactions", testTransactionsInsert)
	t.Run("Transactions", testTransactionsInsertWhitelist)
	t.Run("Types", testTypesInsert)
	t.Run("Types", testTypesInsertWhitelist)
	t.Run("UserTokens", testUserTokensInsert)
	t.Run("UserTokens", testUserTokensInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("TransactionToTypeUsingType", testTransactionToOneTypeUsingType)
	t.Run("TransactionToCategoryUsingCategory", testTransactionToOneCategoryUsingCategory)
	t.Run("UserTokenToUserUsingUser", testUserTokenToOneUserUsingUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("CategoryToTransactions", testCategoryToManyTransactions)
	t.Run("TypeToTransactions", testTypeToManyTransactions)
	t.Run("UserToUserTokens", testUserToManyUserTokens)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("TransactionToTypeUsingTransactions", testTransactionToOneSetOpTypeUsingType)
	t.Run("TransactionToCategoryUsingTransactions", testTransactionToOneSetOpCategoryUsingCategory)
	t.Run("UserTokenToUserUsingUserTokens", testUserTokenToOneSetOpUserUsingUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {
	t.Run("TransactionToTypeUsingTransactions", testTransactionToOneRemoveOpTypeUsingType)
	t.Run("TransactionToCategoryUsingTransactions", testTransactionToOneRemoveOpCategoryUsingCategory)
}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("CategoryToTransactions", testCategoryToManyAddOpTransactions)
	t.Run("TypeToTransactions", testTypeToManyAddOpTransactions)
	t.Run("UserToUserTokens", testUserToManyAddOpUserTokens)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {
	t.Run("CategoryToTransactions", testCategoryToManySetOpTransactions)
	t.Run("TypeToTransactions", testTypeToManySetOpTransactions)
}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {
	t.Run("CategoryToTransactions", testCategoryToManyRemoveOpTransactions)
	t.Run("TypeToTransactions", testTypeToManyRemoveOpTransactions)
}

func TestReload(t *testing.T) {
	t.Run("Categories", testCategoriesReload)
	t.Run("HTTPSessions", testHTTPSessionsReload)
	t.Run("Transactions", testTransactionsReload)
	t.Run("Types", testTypesReload)
	t.Run("UserTokens", testUserTokensReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Categories", testCategoriesReloadAll)
	t.Run("HTTPSessions", testHTTPSessionsReloadAll)
	t.Run("Transactions", testTransactionsReloadAll)
	t.Run("Types", testTypesReloadAll)
	t.Run("UserTokens", testUserTokensReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Categories", testCategoriesSelect)
	t.Run("HTTPSessions", testHTTPSessionsSelect)
	t.Run("Transactions", testTransactionsSelect)
	t.Run("Types", testTypesSelect)
	t.Run("UserTokens", testUserTokensSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Categories", testCategoriesUpdate)
	t.Run("HTTPSessions", testHTTPSessionsUpdate)
	t.Run("Transactions", testTransactionsUpdate)
	t.Run("Types", testTypesUpdate)
	t.Run("UserTokens", testUserTokensUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Categories", testCategoriesSliceUpdateAll)
	t.Run("HTTPSessions", testHTTPSessionsSliceUpdateAll)
	t.Run("Transactions", testTransactionsSliceUpdateAll)
	t.Run("Types", testTypesSliceUpdateAll)
	t.Run("UserTokens", testUserTokensSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
