// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Categories", testCategoriesUpsert)
	t.Run("HTTPSessions", testHTTPSessionsUpsert)
	t.Run("Transactions", testTransactionsUpsert)
	t.Run("Types", testTypesUpsert)
	t.Run("UserTokens", testUserTokensUpsert)
	t.Run("Users", testUsersUpsert)
}
